/**
 * ParkSync - Private Amazon S3 Storage Architecture
 * 
 * ============================================================================
 * PRIVATE S3 STORAGE ARCHITECTURE SPECIFICATION
 * ============================================================================
 * 
 * 1. Bucket Configuration:
 *    - Name: `parksync-private-storage-${process.env.AWS_REGION || 'ap-south-1'}`
 *    - Public Access Block: All 4 settings ENABLED (no public ACLs, no public policies).
 *    - Encryption: Server-Side Encryption with AWS KMS (SSE-KMS) or SSE-S3.
 * 
 * 2. Object Key Hierarchy:
 *    - Host Verification Documents:
 *        `hosts/${hostId}/verification/${filename}`
 *    - Parking Listing Photos:
 *        `hosts/${hostId}/listings/${listingId}/photos/${filename}`
 * 
 * 3. Secure Access:
 *    - Direct client uploads are conducted exclusively via short-lived (15 min)
 *      presigned PUT URLs generated by Lambda for the authenticated `hostId`.
 *    - Permanent public URLs are NEVER exposed or stored.
 */

export const s3StorageService = {
  /**
   * Generate an upload key for a verification document
   */
  getVerificationDocumentKey(hostId, fileName) {
    const sanitized = fileName.replace(/[^a-zA-Z0-9.-]/g, '_');
    return `hosts/${hostId}/verification/${Date.now()}_${sanitized}`;
  },

  /**
   * Generate an upload key for a parking space photo
   */
  getListingPhotoKey(hostId, listingId, fileName) {
    const sanitized = fileName.replace(/[^a-zA-Z0-9.-]/g, '_');
    return `hosts/${hostId}/listings/${listingId}/photos/${Date.now()}_${sanitized}`;
  },

  /**
   * Generate presigned URL for direct S3 upload
   * In local development, returns a simulated presigned upload contract.
   * In production, calls PutObjectCommand via `@aws-sdk/s3-request-presigner`.
   */
  async createPresignedUploadUrl({ hostId, listingId, fileType, fileName, context }) {
    let key;
    if (context === 'verification') {
      key = this.getVerificationDocumentKey(hostId, fileName);
    } else {
      key = this.getListingPhotoKey(hostId, listingId || 'draft', fileName);
    }

    const bucketName = (typeof import.meta !== 'undefined' && import.meta.env?.VITE_PARKSYNC_S3_BUCKET) ||
                       (typeof process !== 'undefined' && process.env?.PARKSYNC_S3_BUCKET) || 
                       'parksync-private-storage';
    const region = (typeof import.meta !== 'undefined' && import.meta.env?.VITE_AWS_REGION) ||
                   (typeof process !== 'undefined' && process.env?.AWS_REGION) || 
                   'ap-south-1';

    // Development presigned payload structure (mirroring AWS S3 presigned PUT contract)
    return {
      uploadUrl: `https://${bucketName}.s3.${region}.amazonaws.com/${key}?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Expires=900`,
      key,
      fileType,
      expiresIn: 900 // 15 minutes
    };
  }
};
